# Configuration file for "Månedens konkurranse" @ nowiki
_extends: sites/nowiki.yml
name: Månedens konkurranse %(year)d-%(month)02d
pages:
    base: Wikipedia:Konkurranser/Månedens konkurranse
    default: Wikipedia:Konkurranser/Månedens konkurranse %(year)d-%(month)02d
    redirect: WP:MK
othersites:
    - nn.wikipedia.org
    - se.wikipedia.org
    - smn.wikipedia.org
    # - www.wikidata.org
    # - commons.wikimedia.org
    # FOR INDIAN CONTEST APRIL 2025 – remove in May
    - bn.wikipedia.org
    - hi.wikipedia.org
    - kn.wikipedia.org
    - syl.wikipedia.org
contestPages:
    resultsSection: 'Resultater|Results'
    participantsSection: 'Delta[kg]ere|Participants'
    footer: "{{Månedens konkurranse %(year)s}}\n[[Kategori:Artikkelkonkurranser]]"
templates:
    contestlist:
        name: Månedens konkurranse
award_messages:
    winner_template: '{{UK vinner|år=%(year)s|måned=%(month)s|%(awards)s}}'
    participant_template: '{{UK deltaker|år=%(year)s|måned=%(month)s|%(awards)s}}'
    organizer_template: '{{UK arrangør|år=%(year)s|måned=%(month)s|%(awards)s|visuk=nei}}'
    reminder_msg: 'Husk at denne månedens konkurranse er [[%(url)s|{{#invoke:UK navboks|contest_name|%(year)d|%(month)d}}]]. Lykke til!'
plot:
    datafile: 'plots/Nowp Månedens konkurranse %(year)d-%(month)02d.json'
    figname: 'plots/Nowp Månedens konkurranse %(year)d-%(month)02d.svg'
    description: |
        == {{int:filedesc}} ==
        {{Information
        |Description    = {{no|1=Resultater for Månedens konkurranse [[:no:%(pagename)s|%(year)s-%(month)s]]}}
                          {{en|1=Results from the monthly article writing contest at Norwegian Bokmål/Nynorsk Wikipedia [[:no:%(pagename)s|%(year)s-%(month)s]]}}
        |Source         = {{own}}
        |Date           = %(start)s
        |Author         = [[User:UKBot|UKBot]]
        }}
        
        == {{int:license-header}} ==
        {{PD-self}}
        
        [[Category:Månedens konkurranse %(year)s]]
