_extends: default.yml
locale: [en_US]
homesite: en.wikipedia.org
default_prefix: en
wikidata_languages: ['en']
pages:
    catignore: User:UKBot/ignored categories
    active_contests_category: Category:UKB active contests
contestPages:
    resultsSection: Results
    participantsSection: 'Participants'
    footer: "[[Category:UKBot contests]]"
templates:
    botinfo: UKB botinfo
    status: UKB status
    commonargs:
        year: year
        week: week
        week2: week2
        yes: yes
        no: no
    infobox:
        name: UKB infobox
        status: status
        start: start
        end: end
        organizer: organizer
        winner: winner
    suspended:
        name: UKB participant suspended
    disqualified:
        name: UKB contribution disqualified
    penalty:
        name: UK points penalty
    bonus:
        name: UK points
    rule:
        name: UKB points
        new: new
        redirect: redirect
        regexp: regexp
        section: section
        qualified: qualified
        contrib: edit
        byte: byte
        word: word
        maxpoints: maxpoints
        site: site
        image: image
        external_link: external link
        ref: citation
        templateremoval: template removal
        bytebonus: bytebonus
        wordbonus: wordbonus
        alias: alias
        own: self-uploaded
        ownwork: own-work
        maxinitialcount: initial limit
        wikidata: wikidata
        properties: properties
        labels: labels
        aliases: aliases
        descriptions: descriptions
        description: description
        require_reference: require_reference
        all: alle
    filters:
        name: UKB criterion
        params:
            new:
                name: new
                params:
                    redirects: redirects
            existing:
                name: existing
            template:
                name: template
            bytes:
                name: bytes
            category:
                name: category
                ignore_page: User:UKBot/ignored categories
                params:
                    ignore: exclude
                    maxdepth: maxdepth
            backlink:
                name: backlink
            forwardlink:
                name: forwardlink
            pages:
                name: pages
            namespace:
                name: namespace
                params:
                    site: site
            sparql:
                name: sparql  # as in {{ ukb criterion | sparql }}
                params:
                    query: query    # as in {{ ukb criterion | sparql | query=... }}
awards:
    blå: { file: Article blue.svg, winner: true }
    rød: { file: Article red.svg, winner: true }
    gul: { file: Article yellow.svg, organizer: true }
    oransj: { file: Article orange.svg, winner: true }
    orange: { file: Article orange.svg, winner: true }
    grønn: { file: Article green.svg }
    grå: { file: Article grey.svg }
    lyslilla: { file: Article MediumPurple.svg }
    lilla: { file: Article purple.svg }
    brun: { file: Article brown.svg }
award_messages:
    winner_template: '{{UK winner|year=%(year)s|week=%(week)s|%(award)s=yes}}'
    participant_template: '{{UK participant|year=%(year)s|week=%(week)s|%(award)s=yes}}'
    organizer_template: '{{UK organizer|year=%(year)s|week=%(week)s|%(award)s=yes|showuk=no}}'
awardstatus:
    pagename: Bruker:UKBot/Premieutsendelse
    wait: Venter
    send: Send ut
    sent: Sendt
